<?php

namespace DemandeBundle\Repository;

/**
 * PlanifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanifRepository extends \Doctrine\ORM\EntityRepository
{
}
