<?php

namespace DemandeBundle\Repository;

/**
 * UrgenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrgenceRepository extends \Doctrine\ORM\EntityRepository
{
}
