integration_index:
    path:     /
    defaults: { _controller: "DemandeBundle:Integration:index" }
    methods:  GET

integration_show:
    path:     /{id}/show
    defaults: { _controller: "DemandeBundle:Integration:show" }
    methods:  GET

integration_new:
    path:     /new/{id}
    defaults: { _controller: "DemandeBundle:Integration:new" }
    methods:  [GET, POST]

integration_edit:
    path:     /{id}/edit
    defaults: { _controller: "DemandeBundle:Integration:edit" }
    methods:  [GET, POST]

integration_delete:
    path:     /{id}/delete
    defaults: { _controller: "DemandeBundle:Integration:delete" }
    methods:  DELETE
