security:
    access_control:
        -
            path: ^/$
            roles:
                - IS_AUTHENTICATED_ANONYMOUSLY
        -
            path: ^/self/register$
            roles:
                - IS_AUTHENTICATED_ANONYMOUSLY
        -
            path: ^/resetting$
            roles:
                - IS_AUTHENTICATED_ANONYMOUSLY
        -
            path: ^/account$
            roles:
                - ROLE_ADMIN
        -
            path: ^/account$
            roles:
                - ROLE_ADMIN
                - ROLE_DEMANDEUR
                - ROLE_DASHBOARD
