fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
app:
    resource: '@AppBundle/Controller/'
    type: annotation 

demande:
    resource: "@DemandeBundle/Resources/config/routing.yml"
    prefix:   /


user_utilisateur:
    resource: "@UserBundle/Controller/UtilisateurController.php"
    type:     annotation

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

    
